app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from products.views import *
from reportes.views import pdflogin, pdfattempts,pdfinventario,pdfventas
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

urlpatterns = [
    path('', LoginView.as_view(template_name='autenticacion/acceder.html'), name='acceder'),
    path('admin/', admin.site.urls),
    path('acceder/', LoginView.as_view(template_name='autenticacion/acceder.html'), name='acceder'),
    path('logout/', LogoutView.as_view(template_name='autenticacion/acceder.html'), name='logout'),
    path('autenticacion/', include('autenticacion.urls')),
    path('products/', listado_productos, name='products'),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('products/', include('products.urls'), name='products'),

    path('reporte-login/', pdflogin, name='pdflogin'),
    path('reporte-intentos/', pdfattempts, name='intentos'),
    path('reporte-inventario/', pdfinventario, name='inventario'),
    path('reporte-ventas/', pdfventas, name='pdfventas'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path('add_product/<int:product_id>/', add_product, name='add_product'),
    path('remove_product/<int:product_id>/', remove_product, name='remove_product'),
    path('decrement_product/<int:product_id>/', decrement_product, name='decrement_product'),
    path('clear/', clear_cart, name='clear_cart'),
]

app/cart/models.py
from django.db import models

# Create your models here.

app/cart/views.py
from django.shortcuts import redirect
from products.models import Product
from django.contrib.auth.decorators import login_required
from .cart import Cart


@login_required(login_url="/autenticacion/login")
def add_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.add(product=product)
    return redirect("listado_productos")


@login_required(login_url="/autenticacion/login")
def remove_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.remove(product)
    return redirect("listado_productos")


@login_required(login_url="/autenticacion/login")
def decrement_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.decrement(product=product)
    return redirect("listado_productos")


@login_required(login_url="/autenticacion/login")
def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    return redirect("listado_productos")

templates/cart/detail.html
{% extends 'layouts/tienda.html' %}
{% load static %}
 
{% block title %}
    Carrito de Compras
{% endblock %}
 
{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                    {% if product.image %}{{ product.image.url }}{% else %}{% static "shop/img/no_image.png" %}{% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>
                        <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                    </td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="button light">Continue
            shopping</a>
        <a href="#" class="button">Checkout</a>
    </p>
{% endblock %}  

templates/cart/widget.html
{% load cart_tags %}
<table class="table table-bordered">
     <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carrito de compras
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.cart.items %}
           {% for key, value in request.session.cart.items %}
                <tr class="text-center">
                    <td>{{ value.name }}</td>
                    <td>{{ value.quantity }}</td>
                    <td>
                        <a
                            href="{% url 'cart:add_product' value.product_id %}"
                            class="btn btn-sm btn-success"
                        >
                            +
                        </a>
                        <a
                            href="{% url 'cart:decrement_product' value.product_id %}"
                            class="ml-2 btn-sm btn btn-danger"
                        >
                            -
                        </a>
                        Total {{ value.price|multiply:value.quantity|money_format:"Q" }}
                    </td>
                </tr>
           {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        No tienes productos en el carrito
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{ cart_total_amount|money_format:"Q" }}
            </td>
        </tr>
        {% if request.session.cart.items %}
            <tr>
                <td colspan="3">
                    <a href="{% url "process_order" %}" class="btn btn-success">Crear pedido</a>
                </td>
            </tr>
        {% endif %}
    </tfoot>
</table>